"""Add new tables

Revision ID: a38ddbb3b29b
Revises: 6388dea60feb
Create Date: 2026-01-04 10:45:36.409025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a38ddbb3b29b'
down_revision: Union[str, Sequence[str], None] = '6388dea60feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # This migration originally tried to recreate tables that were already created
    # in revision 6388dea60feb. Those operations have been removed.
    # If there was an old 'jobs' table (not 'jobs_table'), drop it conditionally.
    # Note: The first migration creates 'jobs_table', not 'jobs', so this is likely
    # a no-op, but we include it for safety in case of legacy data.
    op.execute("DROP TABLE IF EXISTS jobs")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stored_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.drop_table('jobs_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
